"""Add Corpus

Revision ID: 50b3a7b71646
Revises: caf00fdc77bb
Create Date: 2017-05-15 12:29:57.379558

"""

# revision identifiers, used by Alembic.
revision = '50b3a7b71646'
down_revision = 'caf00fdc77bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('classroom', sa.Column('corpus_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classroom', 'corpus', ['corpus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classroom', type_='foreignkey')
    op.drop_column('classroom', 'corpus_id')
    op.drop_table('corpus')
    # ### end Alembic commands ###
